### ISSUE TITLE
 16 UNAUTHENTICATED: Failed to retrieve auth metadata 

### ISSUE THREAD

**Issue by Marcioghiraldelli** [eheikes/tts#124]
I'm trying to use the gcp option, but when configuring private-key and email it gives the error when converting the audio.

  Convert to audio (0/1)
     → 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: error:0909006C:PEM routines:get_name:no start line

The command used is
echo 'Text test' | tts /var/lib/docker/volumes/azuracast_station_data/_data/radio_luna/Noticias_Rss/Noticias_Rss-ok.mp3 --email xxx@gmail.com --private-key key generated in the service --service gcp --voice en-BR -Wavenet-B

**Comment by Marcioghiraldelli** [comment]
I changed the scheme to authenticate by .json file and it also gives the same error.

**Comment by eheikes** [comment]
The PEM error makes it sound like your private key is malformed. Double-check that it is in PEM or PKCS#12 format. See https://github.com/eheikes/tts/blob/master/packages/tts-cli/docs/options.md#--private-key----private-key-file.

You can use a tool like `openssl` to confirm the format, e.g.:

```
openssl rsa -text -in your-private-key.pem -noout
```
