### ISSUE TITLE
audio files and text

### ISSUE THREAD

**Issue by yondu22** [eheikes/tts#48]
Can you share the audio files you generated with polly and corresponding text?

**Comment by yondu22** [comment]
I am looking for audiobooks made with amazon or google tts. I want to do some experiments and put that data into diferent TTS systems, tacotron, tacotron2, voiceloop, merlin and see if it sounds like the original

**Comment by eheikes** [comment]
The [AWS Polly website](https://aws.amazon.com/polly/) has examples of audio and the corresponding text. To generate the audio for a specific text sample, it's fairly easy to [download and use](https://github.com/eheikes/tts/tree/master/packages/tts-cli#requirements--installation) this tool itself. Hope that helps.
