### ISSUE TITLE
Add support for the new Polly engine tag --engine to select neural or standard voice

### ISSUE THREAD

**Issue by sonodave** [eheikes/tts#49]
I have tried to  add the option --engine neural manually to the TTS command string and it does not seem to invoke the neural voice.  Does support for this option need to be added on your end?

**Comment by eheikes** [comment]
Yes, it'll have to be added. Thanks for reporting that -- I'll see if I can get that added soon.

Ref: https://docs.aws.amazon.com/polly/latest/dg/NTTS-main.html

**Comment by eheikes** [comment]
This is available in v1.8.0 now. Check [the docs](https://github.com/eheikes/tts/blob/master/packages/tts-cli/docs/options.md#--engine) for details. Run `npm i tts-cli@1.8.0 -g` to update.

**Comment by sonodave** [comment]
Thank you so much for the work you put into this. I have converted over 1500 hours of audio using your tools and it has saved me so much time.
    On Friday, January 10, 2020, 02:20:13 AM EST, Eric Heikes <notifications@github.com> wrote:  
 
 
This is available in v1.8.0 now. Check the docs for details. Run npm i tts-cli@1.8.0 -g to update.
