### ISSUE TITLE
Engine String? (Neural vs Standard)

### ISSUE THREAD

**Issue by wonderfullyrich** [eheikes/tts#60]
I was taking a look at the new voices Polly has and was wondering how I would add the 'engine' string to the aws-tts line? 

from: [polly-SynthesizeSpeech-request-VoiceId](https://docs.aws.amazon.com/polly/latest/dg/API_SynthesizeSpeech.html#polly-SynthesizeSpeech-request-VoiceId)
 ```
Engine

    Specifies the engine (standard or neural) for Amazon Polly to use when processing input text for speech synthesis. Using a voice that is not supported for the engine selected will result in an error.

    Type: String

    Valid Values: standard | neural 
```

**Comment by wonderfullyrich** [comment]
My apologizes, it's in the docs as '--engine neural'.  I didn't see it in the root README.md.

**Comment by eheikes** [comment]
> I didn't see it in the root README.md.

That's probably an oversight on my part; it should be mentioned there.
