### ISSUE TITLE
The typing on SSML triggers page to refresh

### ISSUE THREAD

**Issue by vashisth00** [eheikes/tts#61]
The SSML audio repeats on typing on input text form

`
  handleChange = e => {
    //e.preventDefault();
    this.props.updateState({
      type: 'CAPTURE_RESPONSE',
      payload: e.target.value
    })
  }`

**Comment by eheikes** [comment]
Sorry, I'm not sure what you're referring too. This project is a command-line tool (for the console), so there's no input field. I don't know the code you mentioned.
